In [3]:
import numpy as np
import pandas as pd
from sklearn.svm import SVR
import seaborn as sns
import matplotlib.pyplot as plt

In [30]:
player_df = pd.read_csv('data.csv')
cols = ['Overall','Age','Potential','Value','Wage']
player_df = player_df[cols]
# player_df.head()

def wage_split(x):
    try:
        return int(x.split("K")[0][1:])
    except:
        return 0

player_df['Wage'] = player_df['Wage'].apply(lambda x : wage_split(x))
def value_split(x):
    try:
        if 'M' in x:
            return float(x.split("M")[0][1:])
        elif 'K' in x:
            return float(x.split("K")[0][1:])/1000
    except:
        return 0
    
player_df['Value'] = player_df['Value'].apply(lambda x : value_split(x))
# player_df['Value'].head()
player_df = player_df.dropna()
player_df.head()
player_df.isnull().any()

Overall      False
Age          False
Potential    False
Value        False
Wage         False
dtype: bool

In [39]:
X = player_df[['Potential','Age','Value']].values
y = player_df['Overall'].values

from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn import metrics

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=99)

In [40]:
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [41]:
print(regressor.intercept_)
print(regressor.coef_)

-15.667871474476954
[0.81474718 0.92789945 0.20466919]

In [42]:
y_pred = regressor.predict(X_test)

df = pd.DataFrame({'Actual': y_test.flatten(), 'Predicted': y_pred.flatten()})
df

      Actual  Predicted
0         58  60.368721
1         66  63.296879
2         69  67.695768
3         62  65.503976
4         67  65.653552
...      ...        ...
3586      72  75.618791
3587      59  63.351868
3588      71  69.167793
3589      63  61.600867
3590      67  65.581334

[3591 rows x 2 columns]

In [43]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 2.014405487437235
Mean Squared Error: 6.520263266597733
Root Mean Squared Error: 2.5534806180188117